core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm
from django.contrib.auth.views import LogoutView

app_name = "core"
urlpatterns = [
    path("", views.index, name="index"),
    path("contact/", views.contact, name="contact"),
    path("signup/", views.signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="core/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
]

item/urls.py
from django.urls import path
from . import views


app_name = "item"
urlpatterns = [
    path("", views.items, name="items"),
    path("new/", views.new, name="new"),
    path("<int:pk>/", views.detail, name="item-detail"),
    path("<int:pk>/delete/", views.delete, name="item-delete"),
    path("<int:pk>/edit/", views.edit, name="item-edit"),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("items/", include("item.urls")),
    path("dashboar/", include("dashboard.urls")),
    path("inbox/", include("conversation.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Your password",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your username",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Your email address",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Your password",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Repeat password",
                "class": "w-full py-4 px-6 rounded-xl",
            }
        )
    )

core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item
from .forms import SignUpForm


def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(
        request,
        "core/index.html",
        {
            "categories": categories,
            "items": items,
        },
    )


def contact(request):
    return render(request, "core/contact.html")


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect("/login/")
    else:
        form = SignUpForm()

    return render(request, "core/signup.html", {"form": form})

core/templates/core/contact.html
{% extends "base.html" %}

{% block title %}Contact{% endblock title %}

{% block content %}
  <h1>The Contact page</h1>
{% endblock content %}

core/templates/core/index.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock title %}

{% block content %}
  <div class="mt-6 py-12 bg-gray-100 rounded-xl px-6">
    <h2 class="mb-12 text-2xl text-center">Newest items</h2>

    <div class="grid grid-cols-3 gap-3">
      {% for item in items %}
        <div>
          <a href="{% url 'item:item-detail' item.id %}">
            <div>
              <img src="{{ item.image.url }}" class="rounded-t-xl" />
            </div>

            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-2xl">{{ item.name }}</h2>
              <p class="text-gray-500">Price: ${{ item.price }}</p>
              
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>

  <div class="mt-6 py-12 bg-gray-100 rounded-xl px-6">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>

    <div class="grid grid-cols-3 gap-3">
      {% for category in categories %}
        <div>
          <a href="#">
            <div class="p-6 bg-white rounded-b-xl">
              <h2 class="text-2xl">{{ category.name }}</h2>
              <p class="text-gray-500">{{ category.items.count }}</p>
            </div>
          </a>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

core/templates/core/login.html
{% extends "base.html" %}

{% block title %}Log in{% endblock title %}

{% block content %}
  <div class="w-1/2 my-6 p-7 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
      {% csrf_token %}

      <div class="mb-3">
        <label class="inline-block mb-2">Username</label><br>
        {{ form.username }}
      </div>


      <div class="mb-3">
        <label class="inline-block mb-2">Password</label><br>
        {{ form.password }}
      </div>


      {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
          {% for field in form %}
            {{ field.errors }}
          {% endfor %}

          {{ form.none_field_errors }}
        </div>
      {% endif %}

      <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
  </div>
{% endblock content %}

core/templates/core/signup.html
{% extends "base.html" %}

{% block title %}Sign up{% endblock title %}

{% block content %}
  <div class="w-1/2 my-6 p-7 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
      {% csrf_token %}

      <div class="mb-3">
        <label class="inline-block mb-2">Username</label><br>
        {{ form.username }}
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2">Email</label><br>
        {{ form.email }}
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2">Password</label><br>
        {{ form.password1 }}
      </div>

      <div class="mb-3">
        <label class="inline-block mb-2">Repeat Password</label><br>
        {{ form.password2 }}
      </div>

      {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
          {% for field in form %}
            {{ field.errors }}
          {% endfor %}

          {{ form.none_field_errors }}
        </div>
      {% endif %}

      <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
  </div>
{% endblock content %}