conversation/urls.py
from django.urls import path
from . import views

app_name = "conversation"
urlpatterns = [
    path("", views.inbox, name="inbox"),
    path("<int:pk>/", views.detail, name="detail"),
    path("new/<int:item_pk>/", views.new_conversation, name="new"),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm
from django.contrib.auth.views import LogoutView

app_name = "core"
urlpatterns = [
    path("", views.index, name="index"),
    path("contact/", views.contact, name="contact"),
    path("signup/", views.signup, name="signup"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="core/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [path("", views.index, name="index")]

item/urls.py
from django.urls import path
from . import views


app_name = "item"
urlpatterns = [
    path("", views.items, name="items"),
    path("new/", views.new, name="new"),
    path("<int:pk>/", views.detail, name="item-detail"),
    path("<int:pk>/delete/", views.delete, name="item-delete"),
    path("<int:pk>/edit/", views.edit, name="item-edit"),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("items/", include("item.urls")),
    path("dashboar/", include("dashboard.urls")),
    path("inbox/", include("conversation.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="http://cdn.tailwindcss.com"></script>
  <title>{% block title %}{% endblock title %} | Puddle</title>
</head>
<body>
  <nav id="main-navigation" class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
    <a href="/" class="text-xl font-semibold">Puddle</a>
    <div class="space-x-6">
      <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
      <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

      {% if request.user.is_authenticated %}
      <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
      <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
      <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-gray-200 text-white rounded-xl hover:bg-gray-300">Log out</a>
      {% else %}
      <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
      <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
      {% endif %}
    </div>
  </nav>
  <div class="px-6 py-6">
    {% block content %}
    {% endblock content%}
  </div>

  <footer class="py-6 px-6 flex justify-between bg-gray-800">
    <div class="w-2/3 pr-10">
      <h3 class="mb-5 font-semibold text-gray-400">About</h3>

      <p class="text-lg text-gray-500">Lorem ipsum bla bla bla. Lorem ipsum bla bla bla. Lorem ipsum bla bla bla.</p>
    </div>

    <div class="w-1/3">
      <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

      <ul class="space-y-2">
        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
        <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
        <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
      </ul>
    </div>
  </footer>
</body>
</html>